CREATE TABLE BO_SERVICE_DATA.MASTER_ACCOUNT (
    ID RAW(16) PRIMARY KEY,
    USER_ID RAW(16) NOT NULL,
    BALANCE NUMBER(19, 2) NOT NULL,
    CONSTRAINT FK_USER
        FOREIGN KEY (USER_ID)
        REFERENCES BO_SERVICE_DATA.MASTER_USER(ID)
        ON DELETE CASCADE
);